"""add editor permissions table

Revision ID: 08cd8525283e
Revises: 3d737b2dab89
Create Date: 2026-01-27 05:11:27.200903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cd8525283e'
down_revision = '3d737b2dab89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_editor',
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('invited_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curriculum_id', 'user_id')
    )
    with op.batch_alter_table('curriculum_editor', schema=None) as batch_op:
        batch_op.create_index('ix_curriculum_editor_curriculum', ['curriculum_id'], unique=False)
        batch_op.create_index('ix_curriculum_editor_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum_editor', schema=None) as batch_op:
        batch_op.drop_index('ix_curriculum_editor_user')
        batch_op.drop_index('ix_curriculum_editor_curriculum')

    op.drop_table('curriculum_editor')
    # ### end Alembic commands ###
