"""describe change

Revision ID: 093fa72a9120
Revises: 70e137790ec1
Create Date: 2026-01-26 04:38:37.281554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093fa72a9120'
down_revision = '70e137790ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_school',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_asset_code'))
        batch_op.create_index('ux_access_asset_code', ['code'], unique=True)
        batch_op.create_index('ux_access_asset_curriculum_share', ['curriculum_id'], unique=True, postgresql_where=sa.text("asset_type = 'curriculum_share'"))

    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_curriculum_school_code'), ['school_code'], unique=False)
        batch_op.create_foreign_key(None, 'lesson_school', ['school_code'], ['code'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_curriculum_school_code'))
        batch_op.drop_column('school_code')

    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.drop_index('ux_access_asset_curriculum_share', postgresql_where=sa.text("asset_type = 'curriculum_share'"))
        batch_op.drop_index('ux_access_asset_code')
        batch_op.create_index(batch_op.f('ix_access_asset_code'), ['code'], unique=True)

    op.drop_table('lesson_school')
    # ### end Alembic commands ###
