"""Added lesson rating

Revision ID: 171a193c3719
Revises: fddded3f0d86
Create Date: 2026-02-01 00:36:42.299950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171a193c3719'
down_revision = 'fddded3f0d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_rating_attempt_id'), ['attempt_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lesson_rating_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_rating_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_rating_attempt_id'))

    op.drop_table('lesson_rating')
    # ### end Alembic commands ###
