"""subjects + trivia tables

Revision ID: 2be94f49d8ca
Revises: 25c36d91a91b
Create Date: 2026-01-11 20:24:21.797157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be94f49d8ca'
down_revision = '25c36d91a91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_subject',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trivia_answer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_block_id', sa.String(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('payout_ticks', sa.BigInteger(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_block_id'], ['lesson_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trivia_answer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_lesson_block_id'), ['lesson_block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_user_id'), ['user_id'], unique=False)

    op.create_table('trivia_bad_vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_block_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_block_id'], ['lesson_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_block_id', name='uq_bad_vote_user_block')
    )
    with op.batch_alter_table('trivia_bad_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_lesson_block_id'), ['lesson_block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_access_asset_code'))
        batch_op.drop_index(batch_op.f('ux_access_asset_curriculum_share'), postgresql_where="((asset_type)::text = 'curriculum_share'::text)")

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lesson_subject_code'), ['subject_code'], unique=False)
        batch_op.create_foreign_key(None, 'lesson_subject', ['subject_code'], ['code'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lesson_subject_code'))
        batch_op.drop_column('subject_code')

    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_access_asset_curriculum_share'), ['curriculum_id'], unique=True, postgresql_where="((asset_type)::text = 'curriculum_share'::text)")
        batch_op.create_index(batch_op.f('ux_access_asset_code'), ['code'], unique=True)

    with op.batch_alter_table('trivia_bad_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_subject_code'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_lesson_block_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_created_at'))

    op.drop_table('trivia_bad_vote')
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trivia_answer_user_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_subject_code'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_lesson_block_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_created_at'))

    op.drop_table('trivia_answer')
    op.drop_table('lesson_subject')
    # ### end Alembic commands ###
