"""add subject_code to curriculum

Revision ID: 3e93d8a7677c
Revises: 2be94f49d8ca
Create Date: 2026-01-12 16:03:14.501149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e93d8a7677c'
down_revision = '2be94f49d8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_curriculum_subject_code'), ['subject_code'], unique=False)
        batch_op.create_foreign_key(None, 'lesson_subject', ['subject_code'], ['code'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_curriculum_subject_code'))
        batch_op.drop_column('subject_code')

    # ### end Alembic commands ###
