"""add reddit style feedback page

Revision ID: 4028f4676e4a
Revises: a7c71a4f5b2e
Create Date: 2026-02-27 20:27:40.436505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4028f4676e4a'
down_revision = 'a7c71a4f5b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_post',
            sa.Column('id', sa.Integer(), nullable=False),
            # CHANGE THIS LINE FROM INTEGER TO STRING
            sa.Column('user_id', sa.String(), nullable=False),
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('is_resolved', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
            )

    op.create_table('feedback_vote',
                    sa.Column('id', sa.Integer(), nullable=False),
                    # CHANGE THIS LINE FROM INTEGER TO STRING TOO
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['feedback_post.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_post')
    op.drop_table('feedback_vote')
    # ### end Alembic commands ###
