"""add has_seen_intro to user

Revision ID: 5554025bfe3e
Revises: 4237149e3f7c
Create Date: 2026-02-17 03:51:23.947662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5554025bfe3e'
down_revision = '4237149e3f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('death_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_intro', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('current_login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('has_seen_intro')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('death_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
