"""baseline schema

Revision ID: 70e137790ec1
Revises: 
Create Date: 2026-01-21 05:23:02.912636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e137790ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('unsubscribe_credit_clawback_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_subject',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('monthly_amount_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('transaction_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_type')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('comped_until', sa.DateTime(), nullable=True),
    sa.Column('active_buddy_count', sa.Integer(), nullable=False),
    sa.Column('stripe_balance_cents', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_clawback_pending_cents', sa.Integer(), nullable=False),
    sa.Column('unsubscribe_clawback_pending_txn_id', sa.String(), nullable=True),
    sa.Column('access_level_mult', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('unsubscribe_clawback_pending_txn_id')
    )
    op.create_table('access_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_account_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_account_currency_code'), ['currency_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_account_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('access_txn',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('memo_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_txn_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_txn_context_id'), ['context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_txn_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_txn_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_txn_idempotency_key'), ['idempotency_key'], unique=True)

    op.create_table('analytics_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('props_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_user_id'), ['user_id'], unique=False)

    op.create_table('billing_credit_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('stripe_balance_txn_id', sa.String(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('clawback_eligible', sa.Boolean(), nullable=False),
    sa.Column('clawed_back_cents', sa.Integer(), nullable=False),
    sa.Column('clawed_back_at', sa.DateTime(), nullable=True),
    sa.Column('clawback_stripe_balance_txn_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clawback_stripe_balance_txn_id'),
    sa.UniqueConstraint('stripe_balance_txn_id')
    )
    with op.batch_alter_table('billing_credit_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_credit_grant_user_id'), ['user_id'], unique=False)

    op.create_table('buddy_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('addressee_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_no_self_buddy'),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_buddy_pair')
    )
    with op.batch_alter_table('buddy_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buddy_link_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buddy_link_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buddy_link_status'), ['status'], unique=False)

    op.create_table('lesson',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lesson_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_visibility'), ['visibility'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('access_revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('access_revoked_anchor', sa.String(length=255), nullable=True),
    sa.Column('access_revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('curriculum',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('wallet_account_id', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_account_id'], ['access_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_curriculum_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_wallet_account_id'), ['wallet_account_id'], unique=True)

    op.create_table('lesson_asset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'ref', name='uq_lesson_asset_ref')
    )
    with op.batch_alter_table('lesson_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_asset_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('lesson_block',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_lesson_block_position')
    )
    with op.batch_alter_table('lesson_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_block_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_block_type'), ['type'], unique=False)

    op.create_table('access_asset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_asset_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_asset_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_asset_curriculum_id'), ['curriculum_id'], unique=False)

    op.create_table('curriculum_day_activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('seconds_spent_total', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'user_id', 'day', name='uq_curr_day_user')
    )
    with op.batch_alter_table('curriculum_day_activity', schema=None) as batch_op:
        batch_op.create_index('ix_curr_day_curr_day', ['curriculum_id', 'day'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_day_activity_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_day_activity_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_day_activity_user_id'), ['user_id'], unique=False)

    op.create_table('curriculum_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('phase_title', sa.String(), nullable=True),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'position', name='uq_curriculum_item_position')
    )
    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_item_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_item_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('curriculum_order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price_ticks', sa.BigInteger(), nullable=False),
    sa.Column('qty_initial', sa.Integer(), nullable=False),
    sa.Column('qty_remaining', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("side in ('bid','ask')", name='ck_order_side'),
    sa.CheckConstraint('price_ticks > 0', name='ck_order_price_pos'),
    sa.CheckConstraint('qty_initial > 0', name='ck_order_qty_initial_pos'),
    sa.CheckConstraint('qty_remaining >= 0', name='ck_order_qty_remaining_nonneg'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_order_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_order_side'), ['side'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_order_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_order_book', ['curriculum_id', 'side', 'status', 'price_ticks', 'created_at'], unique=False)

    op.create_table('curriculum_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_manage_ownership', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('shares >= 0', name='ck_curr_owner_shares_nonneg'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'user_id', name='uq_curr_owner')
    )
    with op.batch_alter_table('curriculum_owner', schema=None) as batch_op:
        batch_op.create_index('ix_curr_owner_curr', ['curriculum_id'], unique=False)
        batch_op.create_index('ix_curr_owner_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_owner_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_owner_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_attempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('seconds_spent_total', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('curriculum_id', sa.String(), nullable=True),
    sa.Column('curriculum_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_attempt_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempt_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempt_curriculum_pos'), ['curriculum_pos'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempt_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('market_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_ticks_per_share', sa.BigInteger(), nullable=False),
    sa.Column('qty_shares', sa.Integer(), nullable=False),
    sa.Column('remaining_shares', sa.Integer(), nullable=False),
    sa.Column('locked_an_ticks', sa.BigInteger(), nullable=False),
    sa.Column('locked_shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("side in ('bid','ask')", name='ck_market_order_side'),
    sa.CheckConstraint("status in ('open','canceled','filled','partial')", name='ck_market_order_status'),
    sa.CheckConstraint('price_ticks_per_share > 0', name='ck_market_order_price_pos'),
    sa.CheckConstraint('qty_shares > 0', name='ck_market_order_qty_pos'),
    sa.CheckConstraint('remaining_shares >= 0', name='ck_market_order_rem_nonneg'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_order_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_order_side'), ['side'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_order_user_id'), ['user_id'], unique=False)

    op.create_table('trivia_answer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_block_id', sa.String(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('payout_ticks', sa.BigInteger(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_block_id'], ['lesson_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trivia_answer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_lesson_block_id'), ['lesson_block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_answer_user_id'), ['user_id'], unique=False)

    op.create_table('trivia_bad_vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_block_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_block_id'], ['lesson_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_code'], ['lesson_subject.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_block_id', name='uq_bad_vote_user_block')
    )
    with op.batch_alter_table('trivia_bad_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_lesson_block_id'), ['lesson_block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_trivia_bad_vote_user_id'), ['user_id'], unique=False)

    op.create_table('access_balance',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['access_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['access_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'asset_id')
    )
    with op.batch_alter_table('access_balance', schema=None) as batch_op:
        batch_op.create_index('ix_access_balance_account_asset', ['account_id', 'asset_id'], unique=False)

    op.create_table('access_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['access_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['access_asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['txn_id'], ['access_txn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_entry', schema=None) as batch_op:
        batch_op.create_index('ix_access_entry_account_asset', ['account_id', 'asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entry_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entry_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entry_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_entry_txn_id'), ['txn_id'], unique=False)

    op.create_table('lesson_block_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_block_id', sa.String(), nullable=False),
    sa.Column('last_choice_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('seconds_spent_total', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_block_id'], ['lesson_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'lesson_block_id', name='uq_attempt_block_progress')
    )
    with op.batch_alter_table('lesson_block_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_block_progress_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_block_progress_lesson_block_id'), ['lesson_block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_block_progress_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('curriculum_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_completion', schema=None) as batch_op:
        batch_op.create_index('ix_completion_user_lesson_time', ['user_id', 'lesson_id', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_completion_attempt_id'), ['attempt_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lesson_completion_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_completion_curriculum_pos'), ['curriculum_pos'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_completion_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_completion_user_id'), ['user_id'], unique=False)

    op.create_table('market_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.String(), nullable=False),
    sa.Column('buy_order_id', sa.Integer(), nullable=True),
    sa.Column('sell_order_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('price_ticks_per_share', sa.BigInteger(), nullable=False),
    sa.Column('qty_shares', sa.Integer(), nullable=False),
    sa.Column('ledger_txn_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price_ticks_per_share > 0', name='ck_market_trade_price_pos'),
    sa.CheckConstraint('qty_shares > 0', name='ck_market_trade_qty_pos'),
    sa.ForeignKeyConstraint(['buy_order_id'], ['market_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_txn_id'], ['access_txn.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sell_order_id'], ['market_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_trade_buy_order_id'), ['buy_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trade_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trade_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trade_ledger_txn_id'), ['ledger_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trade_sell_order_id'), ['sell_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_trade_seller_id'), ['seller_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_trade_seller_id'))
        batch_op.drop_index(batch_op.f('ix_market_trade_sell_order_id'))
        batch_op.drop_index(batch_op.f('ix_market_trade_ledger_txn_id'))
        batch_op.drop_index(batch_op.f('ix_market_trade_curriculum_id'))
        batch_op.drop_index(batch_op.f('ix_market_trade_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_market_trade_buy_order_id'))

    op.drop_table('market_trade')
    with op.batch_alter_table('lesson_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_completion_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_completion_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_completion_curriculum_pos'))
        batch_op.drop_index(batch_op.f('ix_lesson_completion_completed_at'))
        batch_op.drop_index(batch_op.f('ix_lesson_completion_attempt_id'))
        batch_op.drop_index('ix_completion_user_lesson_time')

    op.drop_table('lesson_completion')
    with op.batch_alter_table('lesson_block_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_block_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_block_progress_lesson_block_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_block_progress_attempt_id'))

    op.drop_table('lesson_block_progress')
    with op.batch_alter_table('access_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_entry_txn_id'))
        batch_op.drop_index(batch_op.f('ix_access_entry_entry_type'))
        batch_op.drop_index(batch_op.f('ix_access_entry_asset_id'))
        batch_op.drop_index(batch_op.f('ix_access_entry_account_id'))
        batch_op.drop_index('ix_access_entry_account_asset')

    op.drop_table('access_entry')
    with op.batch_alter_table('access_balance', schema=None) as batch_op:
        batch_op.drop_index('ix_access_balance_account_asset')

    op.drop_table('access_balance')
    with op.batch_alter_table('trivia_bad_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_subject_code'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_lesson_block_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_bad_vote_created_at'))

    op.drop_table('trivia_bad_vote')
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trivia_answer_user_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_subject_code'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_lesson_block_id'))
        batch_op.drop_index(batch_op.f('ix_trivia_answer_created_at'))

    op.drop_table('trivia_answer')
    with op.batch_alter_table('market_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_market_order_status'))
        batch_op.drop_index(batch_op.f('ix_market_order_side'))
        batch_op.drop_index(batch_op.f('ix_market_order_curriculum_id'))

    op.drop_table('market_order')
    with op.batch_alter_table('lesson_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempt_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempt_curriculum_pos'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempt_curriculum_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_attempt_completed_at'))

    op.drop_table('lesson_attempt')
    with op.batch_alter_table('curriculum_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_owner_curriculum_id'))
        batch_op.drop_index('ix_curr_owner_user')
        batch_op.drop_index('ix_curr_owner_curr')

    op.drop_table('curriculum_owner')
    with op.batch_alter_table('curriculum_order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_book')
        batch_op.drop_index(batch_op.f('ix_curriculum_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_order_status'))
        batch_op.drop_index(batch_op.f('ix_curriculum_order_side'))
        batch_op.drop_index(batch_op.f('ix_curriculum_order_curriculum_id'))

    op.drop_table('curriculum_order')
    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_item_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_item_curriculum_id'))

    op.drop_table('curriculum_item')
    with op.batch_alter_table('curriculum_day_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_day_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_day_activity_day'))
        batch_op.drop_index(batch_op.f('ix_curriculum_day_activity_curriculum_id'))
        batch_op.drop_index('ix_curr_day_curr_day')

    op.drop_table('curriculum_day_activity')
    with op.batch_alter_table('access_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_asset_curriculum_id'))
        batch_op.drop_index(batch_op.f('ix_access_asset_code'))
        batch_op.drop_index(batch_op.f('ix_access_asset_asset_type'))

    op.drop_table('access_asset')
    with op.batch_alter_table('lesson_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_block_type'))
        batch_op.drop_index(batch_op.f('ix_lesson_block_lesson_id'))

    op.drop_table('lesson_block')
    with op.batch_alter_table('lesson_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_asset_lesson_id'))

    op.drop_table('lesson_asset')
    with op.batch_alter_table('curriculum', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_wallet_account_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subject_code'))
        batch_op.drop_index(batch_op.f('ix_curriculum_code'))

    op.drop_table('curriculum')
    op.drop_table('subscription')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_visibility'))
        batch_op.drop_index(batch_op.f('ix_lesson_subject_code'))
        batch_op.drop_index(batch_op.f('ix_lesson_language_code'))
        batch_op.drop_index(batch_op.f('ix_lesson_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_code'))

    op.drop_table('lesson')
    with op.batch_alter_table('buddy_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buddy_link_status'))
        batch_op.drop_index(batch_op.f('ix_buddy_link_requester_id'))
        batch_op.drop_index(batch_op.f('ix_buddy_link_addressee_id'))

    op.drop_table('buddy_link')
    with op.batch_alter_table('billing_credit_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_credit_grant_user_id'))

    op.drop_table('billing_credit_grant')
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_event_created_at'))

    op.drop_table('analytics_event')
    with op.batch_alter_table('access_txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_txn_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_access_txn_event_type'))
        batch_op.drop_index(batch_op.f('ix_access_txn_context_type'))
        batch_op.drop_index(batch_op.f('ix_access_txn_context_id'))
        batch_op.drop_index(batch_op.f('ix_access_txn_actor_user_id'))

    op.drop_table('access_txn')
    with op.batch_alter_table('access_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_account_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_account_currency_code'))
        batch_op.drop_index(batch_op.f('ix_access_account_account_type'))

    op.drop_table('access_account')
    op.drop_table('user')
    op.drop_table('transaction_tax')
    op.drop_table('plan')
    op.drop_table('lesson_subject')
    op.drop_table('billing_config')
    # ### end Alembic commands ###
