"""add streak fields to user

Revision ID: a7c71a4f5b2e
Revises: 5554025bfe3e
Create Date: 2026-02-17 06:28:10.632461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c71a4f5b2e'
down_revision = '5554025bfe3e'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add columns as nullable first so the DB accepts them
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))

    # 2. Data Migration: Backfill 0 for all existing users
    op.execute('UPDATE "user" SET current_streak = 0 WHERE current_streak IS NULL')

    # 3. Now that every row has a 0, we can safely enforce NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_streak', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_activity_date')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
