"""added StripeWebhookEvent to model

Revision ID: fddded3f0d86
Revises: 08cd8525283e
Create Date: 2026-01-29 21:40:20.801853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddded3f0d86'
down_revision = '08cd8525283e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('api_version', sa.String(length=64), nullable=True),
    sa.Column('livemode', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'received'")),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        "status IN ('received','processed','ignored','error')",
        name='ck_stripe_webhook_event_status'
    )
    )
    with op.batch_alter_table('stripe_webhook_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_webhook_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripe_webhook_event_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripe_webhook_event_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripe_webhook_event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripe_webhook_event_stripe_event_id'), ['stripe_event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_webhook_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_event_stripe_event_id'))
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_event_status'))
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_event_received_at'))
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_event_processed_at'))
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_event_event_type'))

    op.drop_table('stripe_webhook_event')
    # ### end Alembic commands ###
