#!/usr/bin/env bash
set -euo pipefail

# DANGER: wipes DB volume (true hard reset)
docker compose down -v
docker compose up -d

# Ensure migrations folder exists
mkdir -p migrations/versions

# Remove old autogenerated revisions (optional; ensures single baseline)
rm -f migrations/versions/*.py

# Build a baseline migration from models.py
docker compose exec -T web flask --app app:create_app db revision --autogenerate -m "baseline schema"

# Apply it
docker compose exec -T web flask --app app:create_app db upgrade

# Seed invariants
./scripts/seed_core.sh
